### ISSUE TITLE
Themes other than 'Neutral' does not work

### ISSUE THREAD

**Issue by msthtrifork** [bruunand/kantinen#14]
Screenshot:
<img width="940" alt="image" src="https://github.com/user-attachments/assets/995ce003-2e42-4207-95e3-f27ed0bd2bcc">

**Comment by msthtrifork** [comment]
MANGA IS MY FAVORITE, PLEASE FIX!

**Comment by bruunand** [comment]
SEV 1 incident, ping @lajtmaN.

**Comment by bruunand** [comment]
#15 did the trick it seems.
